// <auto-generated />
using System;
using FoodRecipe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodRecipe.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    partial class FoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodRecipe.Models.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodVariety")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Foods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9487b966-ae2f-4bb9-bd1c-71963f6aa4fd"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 923, DateTimeKind.Local).AddTicks(1026),
                            FoodName = "Pizza",
                            FoodPhoto = "",
                            FoodVariety = "Italian",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("45e432a8-d438-4d81-a839-8eebf2b89ec5"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 938, DateTimeKind.Local).AddTicks(8390),
                            FoodName = "Burger",
                            FoodPhoto = "",
                            FoodVariety = "American",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("73f3f9eb-9404-4615-91cf-2989a210df43"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 938, DateTimeKind.Local).AddTicks(8431),
                            FoodName = "Sushi",
                            FoodPhoto = "",
                            FoodVariety = "Japanese",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("fd4e993c-018d-4074-8694-1dd667ed6c86"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 938, DateTimeKind.Local).AddTicks(8432),
                            FoodName = "Pasta",
                            FoodPhoto = "",
                            FoodVariety = "Italian",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("01f0667b-758f-4486-93e1-61269c936d6b"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 938, DateTimeKind.Local).AddTicks(8433),
                            FoodName = "Tacos",
                            FoodPhoto = "",
                            FoodVariety = "Mexican",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("a085e0f3-7eeb-4d2b-b386-89916d848211"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 938, DateTimeKind.Local).AddTicks(8435),
                            FoodName = "Pad Thai",
                            FoodPhoto = "",
                            FoodVariety = "Thai",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("aa7b91dc-37a5-45e1-950a-34499e7df8cf"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 938, DateTimeKind.Local).AddTicks(8436),
                            FoodName = "Chicken Curry",
                            FoodPhoto = "",
                            FoodVariety = "Indian",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("50b104ed-6326-45c3-a0a5-391aa0ef87bc"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 938, DateTimeKind.Local).AddTicks(8437),
                            FoodName = "Falafel",
                            FoodPhoto = "",
                            FoodVariety = "Middle Eastern",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("7d79971c-d259-44b6-946d-f8d0549cd1a0"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 938, DateTimeKind.Local).AddTicks(8439),
                            FoodName = "Chocolate Cake",
                            FoodPhoto = "",
                            FoodVariety = "Dessert",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("e035d222-4d82-482a-bc1e-d08457bc9c4d"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 938, DateTimeKind.Local).AddTicks(8440),
                            FoodName = "Apple Pie",
                            FoodPhoto = "",
                            FoodVariety = "Dessert",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("FoodRecipe.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FoodId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("FoodId1");

                    b.ToTable("Recipes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c4405de-3648-4b07-98fd-04a168e614ed"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(4508),
                            Description = "Prepare the dough and add toppings.",
                            FoodId = new Guid("9487b966-ae2f-4bb9-bd1c-71963f6aa4fd"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("5b505bd7-b888-4dff-963f-ba3c3e64ae1d"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(4975),
                            Description = "Bake in a preheated oven at 220°C for 15 minutes.",
                            FoodId = new Guid("9487b966-ae2f-4bb9-bd1c-71963f6aa4fd"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("34dedd4e-dafd-4343-8f06-912e3c426a9d"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(4980),
                            Description = "Grill the beef patty with salt and pepper.",
                            FoodId = new Guid("45e432a8-d438-4d81-a839-8eebf2b89ec5"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("126e6188-6492-4e70-9164-8dca5a9cc95f"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(4982),
                            Description = "Assemble the burger with lettuce, tomato, and cheese.",
                            FoodId = new Guid("45e432a8-d438-4d81-a839-8eebf2b89ec5"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("61797257-c790-4ebe-bf3e-78cae9339855"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(4984),
                            Description = "Prepare sushi rice with vinegar and sugar.",
                            FoodId = new Guid("73f3f9eb-9404-4615-91cf-2989a210df43"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("ef6bc462-d948-403f-a317-1c241d2a4b72"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(4985),
                            Description = "Roll the rice with fish and seaweed using a bamboo mat.",
                            FoodId = new Guid("73f3f9eb-9404-4615-91cf-2989a210df43"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("4948dc88-f50c-4188-8bee-f3a8d9e98b77"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(4986),
                            Description = "Boil pasta in salted water for 10 minutes.",
                            FoodId = new Guid("fd4e993c-018d-4074-8694-1dd667ed6c86"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("29b54b38-3947-48bb-a42b-2e90932b1f2e"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(4987),
                            Description = "Prepare the sauce with tomatoes and garlic.",
                            FoodId = new Guid("fd4e993c-018d-4074-8694-1dd667ed6c86"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("9c3d8688-7c95-4c91-95fd-865a83fec569"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(5001),
                            Description = "Cook minced meat with taco seasoning.",
                            FoodId = new Guid("01f0667b-758f-4486-93e1-61269c936d6b"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("ebcddb15-4c56-4168-95af-ab5c6f6952b9"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(5003),
                            Description = "Fill tortillas with meat, lettuce, and cheese.",
                            FoodId = new Guid("01f0667b-758f-4486-93e1-61269c936d6b"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("ade2af17-d59a-4e3d-abc9-bbd38e6beaf8"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(5004),
                            Description = "Cook rice noodles until tender.",
                            FoodId = new Guid("a085e0f3-7eeb-4d2b-b386-89916d848211"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("5a9e8a41-11ac-451c-bfe6-dec641e68eec"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(5005),
                            Description = "Stir-fry with shrimp, egg, and Pad Thai sauce.",
                            FoodId = new Guid("a085e0f3-7eeb-4d2b-b386-89916d848211"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("bf92d03f-0f5f-435b-99eb-b25cfdefa22c"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(5006),
                            Description = "Cook chicken pieces with curry spices.",
                            FoodId = new Guid("aa7b91dc-37a5-45e1-950a-34499e7df8cf"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("6b4e7ace-31da-4fa9-99cf-c1e0dc6e4e2e"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(5008),
                            Description = "Add coconut milk and simmer for 20 minutes.",
                            FoodId = new Guid("aa7b91dc-37a5-45e1-950a-34499e7df8cf"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("1cc40591-19c7-42b0-bc97-31dd68b2a7a9"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(5009),
                            Description = "Blend chickpeas with herbs and spices.",
                            FoodId = new Guid("50b104ed-6326-45c3-a0a5-391aa0ef87bc"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("08b9f914-da9c-417a-b522-77c1e517911e"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(5010),
                            Description = "Form balls and deep fry until crispy.",
                            FoodId = new Guid("50b104ed-6326-45c3-a0a5-391aa0ef87bc"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("c235cbd0-d21d-4f00-b251-05feb1f41e3d"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(5013),
                            Description = "Mix cocoa, sugar, and flour into a batter.",
                            FoodId = new Guid("7d79971c-d259-44b6-946d-f8d0549cd1a0"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("7322561d-9507-4c8d-b95a-99c46a54fe5c"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(5015),
                            Description = "Bake at 175°C for 30 minutes and let cool.",
                            FoodId = new Guid("7d79971c-d259-44b6-946d-f8d0549cd1a0"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("5ac93327-cfee-4003-960f-ab5fde088769"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(5016),
                            Description = "Prepare the pie crust and slice apples.",
                            FoodId = new Guid("e035d222-4d82-482a-bc1e-d08457bc9c4d"),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("aa983a03-9eaa-4980-8308-1e181e1d5269"),
                            CreatedDate = new DateTime(2024, 12, 23, 19, 58, 40, 939, DateTimeKind.Local).AddTicks(5018),
                            Description = "Bake at 180°C for 45 minutes until golden brown.",
                            FoodId = new Guid("e035d222-4d82-482a-bc1e-d08457bc9c4d"),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("FoodRecipe.Models.Recipe", b =>
                {
                    b.HasOne("FoodRecipe.Models.Food", null)
                        .WithMany("Recipes")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodRecipe.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId1");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FoodRecipe.Models.Food", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
